# Generated by Django 4.0.4 on 2022-05-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='publishing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publishing Date'),
        ),
    ]
