# Generated by Django 4.0.4 on 2022-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_productcolor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='slug',
        ),
        migrations.AddField(
            model_name='metadata',
            name='meta_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='ideal_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
