# Generated by Django 4.0.4 on 2022-06-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productsize_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='description',
        ),
    ]
