# Generated by Django 4.0.4 on 2022-05-28 12:59

import apps.groups.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, default=apps.groups.models.groups_icon_default_image, null=True, upload_to=apps.groups.models.groups_icon_image, verbose_name='Icon')),
                ('banner', models.ImageField(blank=True, default=apps.groups.models.groups_banner_default_image, null=True, upload_to=apps.groups.models.groups_banner_image, verbose_name='Banner')),
                ('is_main_homepage', models.BooleanField(default=0, verbose_name='Is Main Homepage')),
                ('is_active', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('name',),
            },
        ),
    ]
