# Generated by Django 4.0.4 on 2022-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groups_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='layout',
            field=models.IntegerField(default=1, help_text='1 => Classic, 2 => Compact, 3 => Minimal, 4 => Modern, 5 => Standard, ', verbose_name='Layout'),
        ),
    ]
