# Generated by Django 4.0.4 on 2022-05-07 16:01

import apps.shops.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, default=apps.shops.models.shops_logo_default_image, null=True, upload_to=apps.shops.models.shops_logo_image, verbose_name='Logo')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('cover_image', models.ImageField(blank=True, default=apps.shops.models.shops_cover_default_image, null=True, upload_to=apps.shops.models.shops_cover_image, verbose_name='Cover Image')),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Holder Name')),
                ('account_holder_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Account Holder Email')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Number')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip Code')),
                ('street_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Street Address')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('contact_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Number')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.state')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ('name',),
            },
        ),
    ]
