# Generated by Django 4.0.4 on 2022-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
