# Generated by Django 4.0.4 on 2022-05-04 14:31

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=300, null=True, verbose_name='User Name')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('image', models.ImageField(default=apps.users.models.users_default_image, upload_to=apps.users.models.users_image, verbose_name='Image')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('company', models.TextField(blank=True, max_length=500, null=True, verbose_name='Company Name')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio')),
                ('dob', models.TextField(blank=True, max_length=500, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Login')),
                ('otp', models.CharField(blank=True, max_length=255, null=True, verbose_name='OTP')),
                ('landmark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Landmark')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
            ],
            options={
                'permissions': [('Can customer user permissions', 'access_customerpermissions')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.users',),
        ),
    ]
